language: cpp

compiler: gcc
os: linux
dist: trusty
sudo: required

addons:
  apt:
    sources: [ ubuntu-toolchain-r-test ]
    packages: [ gcc-7, g++-7, lcov, curl ]

install:
  # setup g++ 6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  # install cmake
  - CMAKE_VERSION="3.8"
  - CMAKE_FULL="${CMAKE_VERSION}.0"
  - pushd ~
  - wget "https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_FULL}-Linux-x86_64.tar.gz"
  - tar xf "cmake-${CMAKE_FULL}-Linux-x86_64.tar.gz"
  - export PATH="${PWD}/cmake-${CMAKE_FULL}-Linux-x86_64/bin:${PATH}"
  - popd
  # verify installed versions
  - which cmake
  - cmake --version
  - which g++
  - g++ --version
  - which lcov
  - lcov --version
  - which curl
  - curl --version

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
  - make -j2
  - make coveralls
