language: cpp

compiler:
  - g++
os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq

script:
  - mkdir build
  - cd build
  - cmake .. -DBOOST_ROOT=$BOOST_ROOT -DCMAKE_INSTALL_PREFIX:PATH=~
  - make 
  - make test
