// Copyright (c) 2016 midnightBITS
// This code is licensed under MIT license (see LICENSE for details)

#include <tangle/uri.hpp>
#include <sstream>
#include <gtest/gtest.h>

using namespace std::literals;

namespace tangle::testing {
	using ::testing::TestWithParam;
	using ::testing::ValuesIn;

	struct UriComponentsTest {
		std::string_view url{};
		std::string_view scheme{};
		struct Authority {
			std::string_view auth{};
			std::string_view user{};
			std::string_view password{};
			std::string_view host{};
			std::string_view port{};
		} auth;
		std::string_view path{};
		std::string_view query{};
		std::string_view fragment{};

		friend std::ostream& operator<<(std::ostream& o,
		                                const UriComponentsTest& param) {
			return o << "\"" << param.url << "\" -> {\"" << param.scheme
			         << "\", \"" << param.auth.auth << "\", \"" << param.path
			         << "\", \"" << param.query << "\", \"" << param.fragment
			         << "\"}";
		}
	};

	class UriComponents : public TestWithParam<UriComponentsTest> {};

	TEST_P(UriComponents, Split) {
		auto const& expected = GetParam();
		auto const actual = uri{expected.url};

#define EQ_SV(A, B) ASSERT_EQ(A, B) << "Expected: " << A << " vs. " << B;

		EQ_SV(expected.scheme, actual.scheme());
		EQ_SV(expected.auth.auth, actual.authority());
		EQ_SV(expected.path, actual.path());
		EQ_SV(expected.query, actual.query());
		EQ_SV(expected.fragment, actual.fragment());

		auto const auth = actual.parsed_authority();
		ASSERT_EQ(expected.auth.user, auth.user);
		ASSERT_EQ(expected.auth.password, auth.password);
		ASSERT_EQ(expected.auth.host, auth.host);
		ASSERT_EQ(expected.auth.port, auth.port);
	}

	static const UriComponentsTest uri_components_all[] = {
	    {"?name=value", {}, {}, {}, "?name=value", {}},
	    {"../../../../C/other.file",
	     {},
	     {},
	     "../../../../C/other.file",
	     {},
	     {}},
	    {"../../../C/other.file", {}, {}, "../../../C/other.file", {}, {}},
	    {"../../C/other.file", {}, {}, "../../C/other.file", {}, {}},
	    {"../../some.file", {}, {}, "../../some.file", {}, {}},
	    {"../C/other.file", {}, {}, "../C/other.file", {}, {}},
	    {"../some.file", {}, {}, "../some.file", {}, {}},
	    {"", {}, {}, {}, {}, {}},
	    {"/", {}, {}, "/", {}, {}},
	    {"//example.com/A/B/",
	     {},
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/",
	     {},
	     {}},
	    {"//example.net",
	     {},
	     {"example.net", {}, {}, "example.net", {}},
	     {},
	     {},
	     {}},
	    {"/A/B/../../../some.file", {}, {}, "/A/B/../../../some.file", {}, {}},
	    {"/C/other.file", {}, {}, "/C/other.file", {}, {}},
	    {"/some.file", {}, {}, "/some.file", {}, {}},
	    {"A/../../../some.file", {}, {}, "A/../../../some.file", {}, {}},
	    {"A/B/../../../some.file", {}, {}, "A/B/../../../some.file", {}, {}},
	    {"A/B/../../some.file", {}, {}, "A/B/../../some.file", {}, {}},
	    {"C/other.file", {}, {}, "C/other.file", {}, {}},
	    {"ftp:../C/other.file", "ftp", {}, "../C/other.file", {}, {}},
	    {"ftp://example.com:21/",
	     "ftp",
	     {"example.com:21", {}, {}, "example.com", "21"},
	     "/",
	     {},
	     {}},
	    {"ftp://example.com/",
	     "ftp",
	     {"example.com", {}, {}, "example.com", {}},
	     "/",
	     {},
	     {}},
	    {"ftp:A/B", "ftp", {}, "A/B", {}, {}},
	    {"ftp:A/B/../C/other.file", "ftp", {}, "A/B/../C/other.file", {}, {}},
	    {"ftp:C/other.file", "ftp", {}, "C/other.file", {}, {}},
	    {"http://[::1],80/", "http", {"[::1],80", {}, {}, {}, {}}, "/", {}, {}},
	    {"http://[::1]:/",
	     "http",
	     {"[::1]:", {}, {}, "[::1]", {}},
	     "/",
	     {},
	     {}},
	    {"http://[::1]:8080/",
	     "http",
	     {"[::1]:8080", {}, {}, "[::1]", "8080"},
	     "/",
	     {},
	     {}},
	    {"http://[::1]:8080/",
	     "http",
	     {"[::1]:8080", {}, {}, "[::1]", "8080"},
	     "/",
	     {},
	     {}},
	    {"http://[::1]/", "http", {"[::1]", {}, {}, "[::1]", {}}, "/", {}, {}},
	    {"http://%45xample.com/",
	     "http",
	     {"%45xample.com", {}, {}, "Example.com", {}},
	     "/",
	     {},
	     {}},
	    {"http://127.0.0.1/",
	     "http",
	     {"127.0.0.1", {}, {}, "127.0.0.1", {}},
	     "/",
	     {},
	     {}},
	    {"http://example.com:/",
	     "http",
	     {"example.com:", {}, {}, "example.com", {}},
	     "/",
	     {},
	     {}},
	    {"http://example.com:2b/",
	     "http",
	     {"example.com:2b", {}, {}, "example.com", "2b"},
	     "/",
	     {},
	     {}},
	    {"http://example.com:80/",
	     "http",
	     {"example.com:80", {}, {}, "example.com", "80"},
	     "/",
	     {},
	     {}},
	    {"http://example.com:8080/",
	     "http",
	     {"example.com:8080", {}, {}, "example.com", "8080"},
	     "/",
	     {},
	     {}},
	    {"http://example.com:b2/",
	     "http",
	     {"example.com:b2", {}, {}, "example.com", "b2"},
	     "/",
	     {},
	     {}},
	    {"http://example.com:blah/",
	     "http",
	     {"example.com:blah", {}, {}, "example.com", "blah"},
	     "/",
	     {},
	     {}},
	    {"http://example.com",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     {},
	     {},
	     {}},
	    {"http://example.com/",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/",
	     {},
	     {}},
	    {"HTTP://EXAMPLE.COM/",
	     "HTTP",
	     {"EXAMPLE.COM", {}, {}, "EXAMPLE.COM", {}},
	     "/",
	     {},
	     {}},
	    {"http://example.com/%%30%30",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/%%30%30",
	     {},
	     {}},
	    {"http://example.com/%2500",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/%2500",
	     {},
	     {}},
	    {"http://example.com/%7Euser",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/%7Euser",
	     {},
	     {}},
	    {"http://example.com/~user",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/~user",
	     {},
	     {}},
	    {"http://example.com/A/",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/",
	     {},
	     {}},
	    {"http://example.com/A/B/..",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/..",
	     {},
	     {}},
	    {"http://example.com/A/B/../../../C/../",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/../../../C/../",
	     {},
	     {}},
	    {"http://example.com/A/B/../../../some.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/../../../some.file",
	     {},
	     {}},
	    {"http://example.com/A/B/../../.%2e/C/..",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/../../.%2e/C/..",
	     {},
	     {}},
	    {"http://example.com/A/B/../",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/../",
	     {},
	     {}},
	    {"http://example.com/A/B/../some.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/../some.file",
	     {},
	     {}},
	    {"http://example.com/A/B/.",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/.",
	     {},
	     {}},
	    {"http://example.com/A/B/./",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/./",
	     {},
	     {}},
	    {"http://example.com/A/B/./some.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/./some.file",
	     {},
	     {}},
	    {"http://example.com/A/B/",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/",
	     {},
	     {}},
	    {"http://example.com/A/B/C/other.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/C/other.file",
	     {},
	     {}},
	    {"http://example.com/A/B/some.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/some.file",
	     {},
	     {}},
	    {"http://example.com/A/B/some.file/",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/some.file/",
	     {},
	     {}},
	    {"http://example.com/A/B/some.file/C/other.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/some.file/C/other.file",
	     {},
	     {}},
	    {"http://example.com/A/C/other.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/C/other.file",
	     {},
	     {}},
	    {"http://example.com/A/some.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/some.file",
	     {},
	     {}},
	    {"http://example.com/C/other.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/C/other.file",
	     {},
	     {}},
	    {"http://example.com/Dir/subdir/Fil%65Name.ext",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/Dir/subdir/Fil%65Name.ext",
	     {},
	     {}},
	    {"http://example.com/Dir/subdir/File Name.ext",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/Dir/subdir/File Name.ext",
	     {},
	     {}},
	    {"http://example.com/Dir/subdir/File%20Name.ext",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/Dir/subdir/File%20Name.ext",
	     {},
	     {}},
	    {"http://example.com/Dir/subdir/FileName.ext",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/Dir/subdir/FileName.ext",
	     {},
	     {}},
	    {"http://example.com/Dir/subdir%2Ffake/FileName.ext",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/Dir/subdir%2Ffake/FileName.ext",
	     {},
	     {}},
	    {"http://EXAMPLE.COM/FileName.ext",
	     "http",
	     {"EXAMPLE.COM", {}, {}, "EXAMPLE.COM", {}},
	     "/FileName.ext",
	     {},
	     {}},
	    {"http://example.com/some.file",
	     "http",
	     {"example.com", {}, {}, "example.com", {}},
	     "/some.file",
	     {},
	     {}},
	    {"http://example.net",
	     "http",
	     {"example.net", {}, {}, "example.net", {}},
	     {},
	     {},
	     {}},
	    {"http://example.net/",
	     "http",
	     {"example.net", {}, {}, "example.net", {}},
	     "/",
	     {},
	     {}},
	    {"http://example%2Fslash.com/",
	     "http",
	     {"example%2Fslash.com", {}, {}, "example/slash.com", {}},
	     "/",
	     {},
	     {}},
	    {"http://one-only/",
	     "http",
	     {"one-only", {}, {}, "one-only", {}},
	     "/",
	     {},
	     {}},
	    {"http://one-only/dir/",
	     "http",
	     {"one-only", {}, {}, "one-only", {}},
	     "/dir/",
	     {},
	     {}},
	    {"http://one-only/dir/sub/",
	     "http",
	     {"one-only", {}, {}, "one-only", {}},
	     "/dir/sub/",
	     {},
	     {}},
	    {"http:/C/other.file", "http", {}, "/C/other.file", {}, {}},
	    {"http:C/other.file", "http", {}, "C/other.file", {}, {}},
	    {"https://example.com:443/",
	     "https",
	     {"example.com:443", {}, {}, "example.com", "443"},
	     "/",
	     {},
	     {}},
	    {"https://example.com",
	     "https",
	     {"example.com", {}, {}, "example.com", {}},
	     {},
	     {},
	     {}},
	    {"https://example.com/",
	     "https",
	     {"example.com", {}, {}, "example.com", {}},
	     "/",
	     {},
	     {}},
	    {"https://example.com/A/B/",
	     "https",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/",
	     {},
	     {}},
	    {"https://example.com/A/B/C/other.file",
	     "https",
	     {"example.com", {}, {}, "example.com", {}},
	     "/A/B/C/other.file",
	     {},
	     {}},
	    {"https://example.com/C/other.file",
	     "https",
	     {"example.com", {}, {}, "example.com", {}},
	     "/C/other.file",
	     {},
	     {}},
	    {"https://example.net/",
	     "https",
	     {"example.net", {}, {}, "example.net", {}},
	     "/",
	     {},
	     {}},
	    {"https://server",
	     "https",
	     {"server", {}, {}, "server", {}},
	     {},
	     {},
	     {}},
	    {"https://server/",
	     "https",
	     {"server", {}, {}, "server", {}},
	     "/",
	     {},
	     {}},
	    {"https://server/dir/",
	     "https",
	     {"server", {}, {}, "server", {}},
	     "/dir/",
	     {},
	     {}},
	    {"https://server/dir/leaf",
	     "https",
	     {"server", {}, {}, "server", {}},
	     "/dir/leaf",
	     {},
	     {}},
	    {"https://server/dir/sub/",
	     "https",
	     {"server", {}, {}, "server", {}},
	     "/dir/sub/",
	     {},
	     {}},
	    {"https://server/leaf",
	     "https",
	     {"server", {}, {}, "server", {}},
	     "/leaf",
	     {},
	     {}},
	    {"https:/C/other.file", "https", {}, "/C/other.file", {}, {}},
	    {"https:C/other.file", "https", {}, "C/other.file", {}, {}},
	    {"mailto:user@server", "mailto", {}, "user@server", {}, {}},
	    {"mailto:userA@serverA", "mailto", {}, "userA@serverA", {}, {}},
	    {"mailto:userB@serverB", "mailto", {}, "userB@serverB", {}, {}},
	    {"one-only", {}, {}, "one-only", {}, {}},
	    {"one-only/dir/", {}, {}, "one-only/dir/", {}, {}},
	    {"one-only/dir/leaf", {}, {}, "one-only/dir/leaf", {}, {}},
	    {"one-only/dir/sub/", {}, {}, "one-only/dir/sub/", {}, {}},
	    {"one-only/leaf", {}, {}, "one-only/leaf", {}, {}},
	    {"smb://example.com:445/",
	     "smb",
	     {"example.com:445", {}, {}, "example.com", "445"},
	     "/",
	     {},
	     {}},
	    {"some.file", {}, {}, "some.file", {}, {}},
	    {"ssh://example.com:22/",
	     "ssh",
	     {"example.com:22", {}, {}, "example.com", "22"},
	     "/",
	     {},
	     {}},
	    {"ssh://example.com:95/",
	     "ssh",
	     {"example.com:95", {}, {}, "example.com", "95"},
	     "/",
	     {},
	     {}},
	    {"ssh://example.com/",
	     "ssh",
	     {"example.com", {}, {}, "example.com", {}},
	     "/",
	     {},
	     {}},
	    {"telnet://example.com:23/",
	     "telnet",
	     {"example.com:23", {}, {}, "example.com", "23"},
	     "/",
	     {},
	     {}},
	    {"telnet://example.com/",
	     "telnet",
	     {"example.com", {}, {}, "example.com", {}},
	     "/",
	     {},
	     {}},
	};
	INSTANTIATE_TEST_SUITE_P(All, UriComponents, ValuesIn(uri_components_all));
}  // namespace tangle::testing
